### ISSUE TITLE
Shell Script to Automate Installation

### ISSUE THREAD

**Issue by m0lese** [cmyui/gulag#111]
I was thinking of creating a shell script which will handle the entire [installation](https://github.com/cmyui/gulag#installation-guide) process with proper error handling. What do you think?

**Comment by Atakku** [comment]
i already have a docker container that does that
![:trolley:](https://cdn.discordapp.com/emojis/827946766397603870.png?v=1&size=64)

**Comment by gamerboy80** [comment]
> 
> 
> ![:trolley:](https://camo.githubusercontent.com/6ea1cb7db8384b39cc65fc8a8ead5a1ec16b23164310bd61df46fffed871b5d1/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3832373934363736363339373630333837302e706e673f763d312673697a653d3634)
:trolley:

**Comment by Atakku** [comment]
> > ![:trolley:](https://camo.githubusercontent.com/6ea1cb7db8384b39cc65fc8a8ead5a1ec16b23164310bd61df46fffed871b5d1/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3832373934363736363339373630333837302e706e673f763d312673697a653d3634)
> > :trolley:

![:trolley:](https://cdn.discordapp.com/emojis/827946766397603870.png?v=1&size=64)

**Comment by m0lese** [comment]
@Atakku Why don't you link it then? People don't have to waste time copy pasting commands and changing <change-me> entries.

**Comment by Atakku** [comment]
> @Atakku Why don't you link it then? People don't have to waste time copy pasting commands and changing entries.

https://github.com/cmyui/gulag/issues/82#issuecomment-822758515

**Comment by cmyui** [comment]
Hey, overall I don't think it's really a big concern since most people just set their servers up a single time, but I'd be alright with merging a bash script in provided it's decent :D.. I'd actually prefer it over a docker container just for simplicity, but setting up a new instance of gulag usually only takes me 10-15minutes; it should be much easier than pretty much any other implementation out there since it uses pretty modern dependencies.

**Comment by m0lese** [comment]
Based on your comment. I'm leaving it here, not worth my time.
