### ISSUE TITLE
add CI/CD

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#13]
**BENEFITS** : Better collaboration and software quality.

**Comment by jacksonisiah** [comment]
what's the use case for that

**Comment by Uniminin** [comment]
- You know how to do proper software development:
	- [ ] abstract
	- [ ] brainstorm
	- [ ] Issue tracking
	- [ ] implementation
	- [ ] peer-review
	- [ ] Documentation
	- [ ] Tests implementation
	- [ ] CI optimized
	- [ ] CC
	- [ ] CD

You do research during the abstracting phase.
If you are doing (F)LOSS that is and I like to stage the docs during the implementation.

**Comment by jacksonisiah** [comment]
this didn't answer my question

**Comment by Uniminin** [comment]
Either you are writing perfect code else your software is trash!

**Comment by Uniminin** [comment]
> what's the use case for that
https://github.com/cmyui/gulag/issues/13#issue-722980239
Simplicity.

**Comment by cmyui** [comment]
Hey, do you have any ideas in specific? I mean once gulag is setup it's already a one liner to run the server, even after a git update it should just work™️.. python makes all that stuff pretty easy since theres no compiling or anything to be done.. submodule wise, we only have oppai-ng which has a build script of its own, but will probably only very rarely ever be updated.. maybe static analysis but honestly any ide in 2020 will probably already do this for you.. overall I really don't see much to gain lol

Maybe for cmyui_pkg I could make it push to pypi when I push to git.. could consider that one.
honestly though like gulag setup is already a 5-10 minute job for anyone with some experience..
