### ISSUE TITLE
missing pip modules version in requirements.txt

### ISSUE THREAD

**Issue by Uniminin** [cmyui/gulag#16]
File: https://raw.githubusercontent.com/cmyui/gulag/master/requirements.txt

It's better to specify what python module versions to pull instead of pulling the latest version. 
Things may not work depending on the module versions used on/for development/production and the latest one used by user(s).

## Note: pip does not have true dependency resolution.

**Comment by cmyui** [comment]
Keeping the libraries fully up to date was intentional (the api's they provide are pretty consistent and already complete anyways, so if they changed something it would have to be huge, in which case I would recode to support the new version anyways),, but I should probably add a lower-boundary for versioning to make sure people aren't using anything omega old.. especially for stuff like `cmyui_pkg` that would wreck some havoc lol
