### ISSUE TITLE
Really very beautiful code

### ISSUE THREAD

**Issue by Pure-Peace** [cmyui/gulag#3]
The code is beautiful and well written!
It's the first time I felt reading other people's code is so comfortable

**Comment by cmyui** [comment]
:D Thanks <333

The ugliest part of the codebase is definitely the boilerplate stuff (packet reading/writing, socket handling & request parsing, etc.), because I try to design the actual events to just show the '_flow of information_', while the actual efficiency and complex stuff of gulag is all done in the background (hopefully that you never have to see). This makes events readable and high-level, while not really sacrificing speed..

Other osu! servers almost always use a high-level library to do their web-handling which ends up adding a load of complexity since the library wasn't designed specifically to make an osu server; for example in the case of Ripple, they have a class for each handler, each in a file of its own. With gulag, I decided to make it simply one single function per event, and all in a single file, and I've already found this much easier to work with, and read (especially since the code in the handlers is pretty concise, since all the complex stuff is done in the bg :P).. I think writing everything myself helped me abstract things in simple ways (and probably understand the lower-level stuff better).

Python is really nice, because unlike a lot of other languages, going for readability will usually also give you efficiency; it's designed with readability in mind.

**Comment by Pure-Peace** [comment]
I am very happy to receive your reply, tky <3

In the reply you wrote something about your design ideas, which is really great!
I have a small question. Why did you choose to write a new socket server yourself instead of using a lower-level library like Uvicorn?

In fact, I just think Uvicorn might be faster

https://github.com/cmyui/cmyui_pkg
http://www.uvicorn.org/

**Comment by cmyui** [comment]
At some point I'm probably going to rewrite a lot of it with some flavor of async so it would be more usable for larger-scale servers (like Akatsuki), so I'll keep uvicorn in mind..

Not sure how well single-threaded would do with a few hundred+ users lol, it's surely fast enough for any smaller servers, though.

[async mysql wrapper is already usable probably](https://github.com/cmyui/cmyui_pkg/blob/master/cmyui/mysql.py#L59-L91)..

**Comment by Pure-Peace** [comment]
Thanks!
looking forward to gulag~
