### ISSUE TITLE
GitHub Release for every Minor Version

### ISSUE THREAD

**Issue by memsdm05** [cmyui/gulag#64]
### Reasons
- Better Archiving
- More """professional"""
- Better changelogs

**Comment by cmyui** [comment]
used to do this but it ends up with a lot of bugs pushed to master.. this problem has actually been avoided mostly with my new pushing routine, but i do agree i'm probably not pushing enough releases.. something around ~500 lines change might be ideal for a release i think (rn more like 1-2k per release). i should try to work on specific things rather than.. everything at once.. lol
